name: Go

on:
  push:
    branches: '*'
  pull_request:
    branches: 'master'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build and test
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        cd tscriptify
        go build -v .

    - name: Test
      run: |
        cd typescriptify
        go test -v .
